using System;
using System.Collections.Generic;

namespace DantesInferno
{
    /// <summary>
    /// Provides localized strings for the launcher UI.
    /// Supported languages: English (en), Spanish (es), Portuguese (pt), French (fr), Italian (it).
    /// </summary>
    public static class LauncherLocalizer
    {
        public const string DefaultLanguage = "en";

        public static readonly List<string> SupportedLanguages = new List<string>
        {
            "en", "es", "pt", "fr", "it"
        };

        public static readonly Dictionary<string, string> LanguageDisplayNames = new Dictionary<string, string>
        {
            { "en", "English" },
            { "es", "Espanol" },
            { "pt", "Portugues" },
            { "fr", "Francais" },
            { "it", "Italiano" },
        };

        // String keys used throughout the launcher.
        public const string
            TabPlay = "tab_play",
            TabDlc = "tab_dlc",
            TabControls = "tab_controls",
            TabSettings = "tab_settings",
            TabUpdates = "tab_updates",
            PlaySubtitle = "play_subtitle",
            PlayStatusReady = "play_status_ready",
            PlayButton = "play_button",
            ExitButton = "exit_button",
            SupportDeveloper = "support_developer",
            VersionLabel = "version_label",
            DlcTitle = "dlc_title",
            DlcDescription = "dlc_description",
            OpenDlcFolder = "open_dlc_folder",
            OpenTuFolder = "open_tu_folder",
            DlcFolderEmpty = "dlc_folder_empty",
            DlcFolderFound = "dlc_folder_found",
            TuInstalled = "tu_installed",
            TuNotFound = "tu_not_found",
            ControlsTitle = "controls_title",
            ControlsHint = "controls_hint",
            GroupActions = "group_actions",
            GroupShoulders = "group_shoulders",
            GroupLeftStick = "group_left_stick",
            GroupRightStick = "group_right_stick",
            GroupDpad = "group_dpad",
            LabelA = "label_a",
            LabelB = "label_b",
            LabelX = "label_x",
            LabelY = "label_y",
            LabelBack = "label_back",
            LabelStart = "label_start",
            LabelLeftShoulder = "label_left_shoulder",
            LabelRightShoulder = "label_right_shoulder",
            LabelLeftTrigger = "label_left_trigger",
            LabelRightTrigger = "label_right_trigger",
            LabelUp = "label_up",
            LabelDown = "label_down",
            LabelLeft = "label_left",
            LabelRight = "label_right",
            LabelPressSprint = "label_press_sprint",
            LabelPress = "label_press",
            BindingsAppliedNote = "bindings_applied_note",
            ResetToDefault = "reset_to_default",
            SaveBindings = "save_bindings",
            GroupGraphics = "group_graphics",
            LabelDisplay = "label_display",
            LabelResolution = "label_resolution",
            LabelRenderer = "label_renderer",
            LabelAntiAliasing = "label_anti_aliasing",
            LabelTextureFiltering = "label_texture_filtering",
            LabelGameLanguage = "label_game_language",
            LabelLauncherLanguage = "label_launcher_language",
            CheckFullscreen = "check_fullscreen",
            GroupControls = "group_controls",
            CheckControllerBackend = "check_controller_backend",
            LabelButtonGlyphs = "label_button_glyphs",
            ComingSoon = "coming_soon",
            CheckLogging = "check_logging",
            SettingsAppliedNote = "settings_applied_note",
            ResetToRecommended = "reset_to_recommended",
            SaveSettings = "save_settings",
            UpdatesTitle = "updates_title",
            InstalledVersion = "installed_version",
            CheckForUpdates = "check_for_updates",
            DownloadInstall = "download_install",
            PlayStatusMissing = "play_status_missing",
            TrialsServerTitle = "trials_server_title",
            TrialsServerMessage = "trials_server_message",
            TrialsServerButton = "trials_server_button",
            ResolutionTooltip = "resolution_tooltip",
            RendererTooltip = "renderer_tooltip",
            LanguageGameTooltip = "language_game_tooltip",
            LanguageLauncherTooltip = "language_launcher_tooltip",
            TuFolderTooltip = "tu_folder_tooltip",
            ControllerTooltip = "controller_tooltip",
            GlyphTooltip = "glyph_tooltip",
            // Installer
            InstTitle = "inst_title",
            InstHeader = "inst_header",
            InstWelcomeTitle = "inst_welcome_title",
            InstWelcomeIntro = "inst_welcome_intro",
            InstWelcomeStep1 = "inst_welcome_step1",
            InstWelcomeStep2 = "inst_welcome_step2",
            InstWelcomeStep3 = "inst_welcome_step3",
            InstWelcomeStep4 = "inst_welcome_step4",
            InstWelcomeStep5 = "inst_welcome_step5",
            InstWelcomeLegal = "inst_welcome_legal",
            InstDestTitle = "inst_dest_title",
            InstDestHint = "inst_dest_hint",
            InstBrowse = "inst_browse",
            InstIsoTitle = "inst_iso_title",
            InstIsoHint = "inst_iso_hint",
            InstProgressTitle = "inst_progress_title",
            InstFinishTitle = "inst_finish_title",
            InstCreateShortcut = "inst_create_shortcut",
            InstBack = "inst_back",
            InstNext = "inst_next",
            InstInstall = "inst_install",
            InstFinish = "inst_finish",
            InstInvalidDestTitle = "inst_invalid_dest_title",
            InstInvalidDestMsg = "inst_invalid_dest_msg",
            InstInvalidIsoTitle = "inst_invalid_iso_title",
            InstInvalidIsoMsg = "inst_invalid_iso_msg",
            InstFolderDialog = "inst_folder_dialog",
            InstIsoDialog = "inst_iso_dialog",
            InstFailedTitle = "inst_failed_title",
            InstFailedMsg = "inst_failed_msg",
            InstShortcutErrorTitle = "inst_shortcut_error_title",
            InstShortcutErrorMsg = "inst_shortcut_error_msg",
            InstFinishSummary = "inst_finish_summary",
            InstPreparing = "inst_preparing",
            InstRemovingOld = "inst_removing_old",
            InstExtracting = "inst_extracting",
            InstSkipExtract = "inst_skip_extract",
            InstCopying = "inst_copying",
            InstCopied = "inst_copied",
            InstUpdatingConfig = "inst_updating_config",
            InstCopyTu = "inst_copy_tu",
            InstTuMissing = "inst_tu_missing",
            InstComplete = "inst_complete";

        private static readonly Dictionary<string, Dictionary<string, string>> _translations;

        static LauncherLocalizer()
        {
            _translations = new Dictionary<string, Dictionary<string, string>>();

            // English
            var en = new Dictionary<string, string>
            {
                { TabPlay, "PLAY" },
                { TabDlc, "DLC" },
                { TabControls, "CONTROLS" },
                { TabSettings, "SETTINGS" },
                { TabUpdates, "UPDATES" },
                { PlaySubtitle, "Ready to enter the Nine Circles." },
                { PlayStatusReady, "Game files found." },
                { PlayStatusMissing, "Game files missing. Run the installer first." },
                { TrialsServerTitle, "Trials of Saint Lucia - Online Server" },
                { TrialsServerMessage, "A dedicated server for the Trials of Saint Lucia DLC is currently in development and will launch in the coming days or weeks. Due to server costs, access will be limited to Ko-Fi members for now. Keep an eye on our Discord for the launch announcement." },
                { TrialsServerButton, "Support on Ko-Fi" },
                { PlayButton, "PLAY" },
                { ExitButton, "EXIT" },
                { SupportDeveloper, "Support the Developer" },
                { VersionLabel, "Version: {0}" },
                { DlcTitle, "Downloadable Content" },
                { DlcDescription, "To install DLC, copy your DLC STFS package files into the DLC folder, then launch the game. The game will automatically install them on startup." },
                { OpenDlcFolder, "Open DLC Folder" },
                { OpenTuFolder, "Open TU Folder" },
                { DlcFolderEmpty, "DLC folder: empty" },
                { DlcFolderFound, "DLC folder: {0} file(s) found" },
                { TuInstalled, "Title Update (default.xexp): installed" },
                { TuNotFound, "Title Update (default.xexp): not found" },
                { ControlsTitle, "Keyboard Bindings" },
                { ControlsHint, "Click a field and press a key to bind it. Use combinations like Shift+Up for D-pad." },
                { GroupActions, "Actions" },
                { GroupShoulders, "Shoulders / Triggers" },
                { GroupLeftStick, "Left Stick (Movement)" },
                { GroupRightStick, "Right Stick (Camera)" },
                { GroupDpad, "D-Pad" },
                { LabelA, "A (Interact):" },
                { LabelB, "B (Cancel):" },
                { LabelX, "X (Attack):" },
                { LabelY, "Y (Magic):" },
                { LabelBack, "Back:" },
                { LabelStart, "Start:" },
                { LabelLeftShoulder, "Left Shoulder:" },
                { LabelRightShoulder, "Right Shoulder:" },
                { LabelLeftTrigger, "Left Trigger:" },
                { LabelRightTrigger, "Right Trigger:" },
                { LabelUp, "Up:" },
                { LabelDown, "Down:" },
                { LabelLeft, "Left:" },
                { LabelRight, "Right:" },
                { LabelPressSprint, "Press (Sprint):" },
                { LabelPress, "Press:" },
                { BindingsAppliedNote, "Bindings are applied when you click PLAY." },
                { ResetToDefault, "Reset to Default" },
                { SaveBindings, "Save Bindings" },
                { GroupGraphics, "Graphics Quality" },
                { LabelDisplay, "Display:" },
                { LabelResolution, "Resolution:" },
                { LabelRenderer, "Renderer:" },
                { LabelAntiAliasing, "Anti-Aliasing:" },
                { LabelTextureFiltering, "Texture Filtering:" },
                { LabelGameLanguage, "Game Language:" },
                { LabelLauncherLanguage, "Launcher Language:" },
                { CheckFullscreen, "Fullscreen" },
                { GroupControls, "Controls" },
                { CheckControllerBackend, "Use SDL controller backend (Xbox / PlayStation controllers)" },
                { LabelButtonGlyphs, "Button glyphs:" },
                { ComingSoon, "Coming soon" },
                { CheckLogging, "Enable logging (for crash reports)" },
                { SettingsAppliedNote, "Settings are applied when you click PLAY." },
                { ResetToRecommended, "Reset to Recommended" },
                { SaveSettings, "Save Settings" },
                { UpdatesTitle, "Check for Updates" },
                { InstalledVersion, "Installed version: {0}" },
                { CheckForUpdates, "Check for Updates" },
                { DownloadInstall, "Download & Install" },
                { ResolutionTooltip, "Internal render resolution. 'Auto' matches your display height. Other values are display-equivalent; the game renders at 16:9 pixels and is stretched to your monitor's aspect ratio." },
                { RendererTooltip, "ReXGlue = original D3D12 plugin renderer. Native = in-process Vulkan Xenos renderer." },
                { LanguageGameTooltip, "Game language. Only languages present on the disc are listed. English is always available when present." },
                { LanguageLauncherTooltip, "Language for the launcher interface." },
                { TuFolderTooltip, "Opens the game folder where default.xexp (Title Update) must be placed." },
                { ControllerTooltip, "Checked = SDL3 (all controller families). Unchecked = XInput (Xbox pads only)." },
                { GlyphTooltip, "Coming soon" },
                { InstTitle, "Dante's Inferno - Installer" },
                { InstHeader, "DANTE'S INFERNO - INSTALLER" },
                { InstWelcomeTitle, "Welcome to the Nine Circles." },
                { InstWelcomeIntro, "This installer will:" },
                { InstWelcomeStep1, "- Ask for the destination folder" },
                { InstWelcomeStep2, "- Ask for your original game ISO" },
                { InstWelcomeStep3, "- Extract the ISO into the destination" },
                { InstWelcomeStep4, "- Copy the PC port files into the destination" },
                { InstWelcomeStep5, "- Create a desktop shortcut" },
                { InstWelcomeLegal, "You must own a legal copy of the Xbox 360 game disc or ISO." },
                { InstDestTitle, "Choose Installation Folder" },
                { InstDestHint, "The game will be installed into this folder." },
                { InstBrowse, "Browse" },
                { InstIsoTitle, "Select Game ISO" },
                { InstIsoHint, "Select a Dante's Inferno Xbox 360 ISO file (XISO)." },
                { InstProgressTitle, "Installing..." },
                { InstFinishTitle, "Installation Complete" },
                { InstCreateShortcut, "Create desktop shortcut" },
                { InstBack, "Back" },
                { InstNext, "Next" },
                { InstInstall, "Install" },
                { InstFinish, "Finish" },
                { InstInvalidDestTitle, "Invalid Destination" },
                { InstInvalidDestMsg, "Please choose a valid destination folder." },
                { InstInvalidIsoTitle, "Invalid ISO" },
                { InstInvalidIsoMsg, "Please select a valid ISO file." },
                { InstFolderDialog, "Select the installation folder" },
                { InstIsoDialog, "Select Dante's Inferno ISO" },
                { InstFailedTitle, "Install Error" },
                { InstFailedMsg, "Installation failed:\n{0}" },
                { InstShortcutErrorTitle, "Shortcut Error" },
                { InstShortcutErrorMsg, "Could not create desktop shortcut:\n{0}" },
                { InstFinishSummary, "Installed to:\n{0}\n\nGame data extracted to:\n{1}\n\nClick Finish to close the installer." },
                { InstPreparing, "Preparing destination..." },
                { InstRemovingOld, "Removing old game data..." },
                { InstExtracting, "Extracting ISO to game folder (this may take a few minutes)..." },
                { InstSkipExtract, "Game data already present, skipping extraction." },
                { InstCopying, "Copying game files..." },
                { InstCopied, "Copied {0}" },
                { InstUpdatingConfig, "Updating configuration..." },
                { InstCopyTu, "Copying Title Update 2 patch (default.xexp)..." },
                { InstTuMissing, "WARNING: default.xexp not found in payload - TU2 will not be applied." },
                { InstComplete, "Installation complete." },
            };
            _translations["en"] = en;

            // Spanish
            var es = new Dictionary<string, string>
            {
                { TabPlay, "JUGAR" },
                { TabDlc, "DLC" },
                { TabControls, "CONTROLES" },
                { TabSettings, "AJUSTES" },
                { TabUpdates, "ACTUALIZ." },
                { PlaySubtitle, "Listo para entrar a los Nueve Circulos." },
                { PlayStatusReady, "Archivos del juego encontrados." },
                { PlayStatusMissing, "Faltan archivos del juego. Ejecuta el instalador primero." },
                { TrialsServerTitle, "Trials of Saint Lucia - Servidor Online" },
                { TrialsServerMessage, "Un servidor dedicado para el DLC Trials of Saint Lucia esta actualmente en desarrollo y se lanzara en los proximos dias o semanas. Debido a los costos del servidor, el acceso estara limitado a miembros de Ko-Fi por ahora. Esten atentos a nuestro Discord para el anuncio del lanzamiento." },
                { TrialsServerButton, "Apoyar en Ko-Fi" },
                { PlayButton, "JUGAR" },
                { ExitButton, "SALIR" },
                { SupportDeveloper, "Apoya al Desarrollador" },
                { VersionLabel, "Version: {0}" },
                { DlcTitle, "Contenido Descargable" },
                { DlcDescription, "Para instalar DLC, copia tus archivos de paquete STFS de DLC en la carpeta DLC, luego inicia el juego. El juego los instalara automaticamente al arrancar." },
                { OpenDlcFolder, "Abrir Carpeta DLC" },
                { OpenTuFolder, "Abrir Carpeta TU" },
                { DlcFolderEmpty, "Carpeta DLC: vacia" },
                { DlcFolderFound, "Carpeta DLC: {0} archivo(s) encontrado(s)" },
                { TuInstalled, "Actualizacion (default.xexp): instalada" },
                { TuNotFound, "Actualizacion (default.xexp): no encontrada" },
                { ControlsTitle, "Asignaciones de Teclado" },
                { ControlsHint, "Haz clic en un campo y presiona una tecla para asignarla. Usa combinaciones como Shift+Up para el D-pad." },
                { GroupActions, "Acciones" },
                { GroupShoulders, "Hombros / Gatillos" },
                { GroupLeftStick, "Stick Izquierdo (Movimiento)" },
                { GroupRightStick, "Stick Derecho (Camara)" },
                { GroupDpad, "D-Pad" },
                { LabelA, "A (Interactuar):" },
                { LabelB, "B (Cancelar):" },
                { LabelX, "X (Atacar):" },
                { LabelY, "Y (Magia):" },
                { LabelBack, "Atras:" },
                { LabelStart, "Inicio:" },
                { LabelLeftShoulder, "Hombro Izq.:" },
                { LabelRightShoulder, "Hombro Der.:" },
                { LabelLeftTrigger, "Gatillo Izq.:" },
                { LabelRightTrigger, "Gatillo Der.:" },
                { LabelUp, "Arriba:" },
                { LabelDown, "Abajo:" },
                { LabelLeft, "Izquierda:" },
                { LabelRight, "Derecha:" },
                { LabelPressSprint, "Presionar (Correr):" },
                { LabelPress, "Presionar:" },
                { BindingsAppliedNote, "Las asignaciones se aplican al hacer clic en JUGAR." },
                { ResetToDefault, "Restaurar Predeterminado" },
                { SaveBindings, "Guardar Asignaciones" },
                { GroupGraphics, "Calidad Grafica" },
                { LabelDisplay, "Pantalla:" },
                { LabelResolution, "Resolucion:" },
                { LabelRenderer, "Renderizador:" },
                { LabelAntiAliasing, "Anti-Aliasing:" },
                { LabelTextureFiltering, "Filtrado de Textura:" },
                { LabelGameLanguage, "Idioma del Juego:" },
                { LabelLauncherLanguage, "Idioma del Launcher:" },
                { CheckFullscreen, "Pantalla Completa" },
                { GroupControls, "Controles" },
                { CheckControllerBackend, "Usar backend de controlador SDL (Xbox / PlayStation)" },
                { LabelButtonGlyphs, "Glifos de botones:" },
                { ComingSoon, "Proximamente" },
                { CheckLogging, "Habilitar registro (para informes de fallos)" },
                { SettingsAppliedNote, "Los ajustes se aplican al hacer clic en JUGAR." },
                { ResetToRecommended, "Restaurar Recomendado" },
                { SaveSettings, "Guardar Ajustes" },
                { UpdatesTitle, "Buscar Actualizaciones" },
                { InstalledVersion, "Version instalada: {0}" },
                { CheckForUpdates, "Buscar Actualizaciones" },
                { DownloadInstall, "Descargar e Instalar" },
                { ResolutionTooltip, "Resolucion de renderizado interno. 'Auto' coincide con la altura de tu pantalla. Los demas valores son equivalentes de pantalla; el juego renderiza a 16:9 y se estira a la relacion de aspecto de tu monitor." },
                { RendererTooltip, "ReXGlue = renderizador D3D12 original. Native = renderizador in-process Vulkan Xenos." },
                { LanguageGameTooltip, "Idioma del juego. Detectado desde la region XEX del juego. Ingles siempre disponible." },
                { LanguageLauncherTooltip, "Idioma para la interfaz del launcher." },
                { TuFolderTooltip, "Abre la carpeta del juego donde default.xexp (Actualizacion) debe colocarse." },
                { ControllerTooltip, "Marcado = SDL3 (todas las familias de controladores). Desmarcado = XInput (solo pads Xbox)." },
                { GlyphTooltip, "Proximamente" },
                { InstTitle, "Dante's Inferno - Instalador" },
                { InstHeader, "DANTE'S INFERNO - INSTALADOR" },
                { InstWelcomeTitle, "Bienvenido a los Nueve Circulos." },
                { InstWelcomeIntro, "Este instalador:" },
                { InstWelcomeStep1, "- Pedira la carpeta de destino" },
                { InstWelcomeStep2, "- Pedira tu ISO original del juego" },
                { InstWelcomeStep3, "- Extraera la ISO en el destino" },
                { InstWelcomeStep4, "- Copiara los archivos del port a PC" },
                { InstWelcomeStep5, "- Creara un acceso directo en el escritorio" },
                { InstWelcomeLegal, "Debes poseer una copia legal del disco o ISO de Xbox 360." },
                { InstDestTitle, "Elegir Carpeta de Instalacion" },
                { InstDestHint, "El juego se instalara en esta carpeta." },
                { InstBrowse, "Examinar" },
                { InstIsoTitle, "Seleccionar ISO del Juego" },
                { InstIsoHint, "Selecciona un archivo ISO de Dante's Inferno para Xbox 360 (XISO)." },
                { InstProgressTitle, "Instalando..." },
                { InstFinishTitle, "Instalacion Completa" },
                { InstCreateShortcut, "Crear acceso directo en el escritorio" },
                { InstBack, "Atras" },
                { InstNext, "Siguiente" },
                { InstInstall, "Instalar" },
                { InstFinish, "Finalizar" },
                { InstInvalidDestTitle, "Destino Invalido" },
                { InstInvalidDestMsg, "Elige una carpeta de destino valida." },
                { InstInvalidIsoTitle, "ISO Invalida" },
                { InstInvalidIsoMsg, "Selecciona un archivo ISO valido." },
                { InstFolderDialog, "Selecciona la carpeta de instalacion" },
                { InstIsoDialog, "Selecciona la ISO de Dante's Inferno" },
                { InstFailedTitle, "Error de Instalacion" },
                { InstFailedMsg, "La instalacion fallo:\n{0}" },
                { InstShortcutErrorTitle, "Error de Acceso Directo" },
                { InstShortcutErrorMsg, "No se pudo crear el acceso directo:\n{0}" },
                { InstFinishSummary, "Instalado en:\n{0}\n\nDatos del juego extraidos en:\n{1}\n\nHaz clic en Finalizar para cerrar el instalador." },
                { InstPreparing, "Preparando destino..." },
                { InstRemovingOld, "Eliminando datos antiguos del juego..." },
                { InstExtracting, "Extrayendo la ISO a la carpeta del juego (puede tardar unos minutos)..." },
                { InstSkipExtract, "Datos del juego ya presentes, se omite la extraccion." },
                { InstCopying, "Copiando archivos del juego..." },
                { InstCopied, "Copiado {0}" },
                { InstUpdatingConfig, "Actualizando configuracion..." },
                { InstCopyTu, "Copiando parche Title Update 2 (default.xexp)..." },
                { InstTuMissing, "AVISO: default.xexp no encontrado en el payload - TU2 no se aplicara." },
                { InstComplete, "Instalacion completa." },
            };
            _translations["es"] = es;

            // Portuguese
            var pt = new Dictionary<string, string>
            {
                { TabPlay, "JOGAR" },
                { TabDlc, "DLC" },
                { TabControls, "CONTROLES" },
                { TabSettings, "AJUSTES" },
                { TabUpdates, "ATUALIZ." },
                { PlaySubtitle, "Pronto para entrar nos Nove Circulos." },
                { PlayStatusReady, "Arquivos do jogo encontrados." },
                { PlayStatusMissing, "Arquivos do jogo ausentes. Execute o instalador primeiro." },
                { TrialsServerTitle, "Trials of Saint Lucia - Servidor Online" },
                { TrialsServerMessage, "Um servidor dedicado para o DLC Trials of Saint Lucia esta atualmente em desenvolvimento e sera lancado nos proximos dias ou semanas. Devido aos custos do servidor, o acesso sera limitado a membros do Ko-Fi por enquanto. Fiquem atentos ao nosso Discord para o anuncio do lancamento." },
                { TrialsServerButton, "Apoiar no Ko-Fi" },
                { PlayButton, "JOGAR" },
                { ExitButton, "SAIR" },
                { SupportDeveloper, "Apoiar o Desenvolvedor" },
                { VersionLabel, "Versao: {0}" },
                { DlcTitle, "Conteudo Baixavel" },
                { DlcDescription, "Para instalar DLC, copie seus arquivos de pacote STFS de DLC para a pasta DLC e inicie o jogo. O jogo os instalara automaticamente na inicializacao." },
                { OpenDlcFolder, "Abrir Pasta DLC" },
                { OpenTuFolder, "Abrir Pasta TU" },
                { DlcFolderEmpty, "Pasta DLC: vazia" },
                { DlcFolderFound, "Pasta DLC: {0} arquivo(s) encontrado(s)" },
                { TuInstalled, "Atualizacao (default.xexp): instalada" },
                { TuNotFound, "Atualizacao (default.xexp): nao encontrada" },
                { ControlsTitle, "Atribuicoes de Teclado" },
                { ControlsHint, "Clique em um campo e pressione uma tecla para atribuir. Use combinacoes como Shift+Up para o D-pad." },
                { GroupActions, "Acoes" },
                { GroupShoulders, "Ombros / Gatilhos" },
                { GroupLeftStick, "Stick Esquerdo (Movimento)" },
                { GroupRightStick, "Stick Direito (Camera)" },
                { GroupDpad, "D-Pad" },
                { LabelA, "A (Interagir):" },
                { LabelB, "B (Cancelar):" },
                { LabelX, "X (Atacar):" },
                { LabelY, "Y (Magia):" },
                { LabelBack, "Voltar:" },
                { LabelStart, "Inicio:" },
                { LabelLeftShoulder, "Ombro Esq.:" },
                { LabelRightShoulder, "Ombro Dir.:" },
                { LabelLeftTrigger, "Gatilho Esq.:" },
                { LabelRightTrigger, "Gatilho Dir.:" },
                { LabelUp, "Cima:" },
                { LabelDown, "Baixo:" },
                { LabelLeft, "Esquerda:" },
                { LabelRight, "Direita:" },
                { LabelPressSprint, "Pressionar (Correr):" },
                { LabelPress, "Pressionar:" },
                { BindingsAppliedNote, "As atribuicoes sao aplicadas ao clicar em JOGAR." },
                { ResetToDefault, "Restaurar Padrao" },
                { SaveBindings, "Salvar Atribuicoes" },
                { GroupGraphics, "Qualidade Grafica" },
                { LabelDisplay, "Tela:" },
                { LabelResolution, "Resolucao:" },
                { LabelRenderer, "Renderizador:" },
                { LabelAntiAliasing, "Anti-Aliasing:" },
                { LabelTextureFiltering, "Filtragem de Textura:" },
                { LabelGameLanguage, "Idioma do Jogo:" },
                { LabelLauncherLanguage, "Idioma do Launcher:" },
                { CheckFullscreen, "Tela Cheia" },
                { GroupControls, "Controles" },
                { CheckControllerBackend, "Usar backend de controle SDL (Xbox / PlayStation)" },
                { LabelButtonGlyphs, "Glifos de botoes:" },
                { ComingSoon, "Em breve" },
                { CheckLogging, "Habilitar registro (para relatorios de falhas)" },
                { SettingsAppliedNote, "Os ajustes sao aplicados ao clicar em JOGAR." },
                { ResetToRecommended, "Restaurar Recomendado" },
                { SaveSettings, "Salvar Ajustes" },
                { UpdatesTitle, "Verificar Atualizacoes" },
                { InstalledVersion, "Versao instalada: {0}" },
                { CheckForUpdates, "Verificar Atualizacoes" },
                { DownloadInstall, "Baixar e Instalar" },
                { ResolutionTooltip, "Resolucao de renderizacao interna. 'Auto' corresponde a altura da sua tela. Os outros valores sao equivalentes de tela; o jogo renderiza em 16:9 e e esticado para a proporcao do seu monitor." },
                { RendererTooltip, "ReXGlue = renderizador D3D12 original. Native = renderizador Vulkan Xenos in-process." },
                { LanguageGameTooltip, "Idioma do jogo. Detectado pela regiao XEX do jogo. Ingles sempre disponivel." },
                { LanguageLauncherTooltip, "Idioma para a interface do launcher." },
                { TuFolderTooltip, "Abre a pasta do jogo onde default.xexp (Atualizacao) deve ser colocado." },
                { ControllerTooltip, "Marcado = SDL3 (todas as familias de controles). Desmarcado = XInput (apenas controles Xbox)." },
                { GlyphTooltip, "Em breve" },
                { InstTitle, "Dante's Inferno - Instalador" },
                { InstHeader, "DANTE'S INFERNO - INSTALADOR" },
                { InstWelcomeTitle, "Bem-vindo aos Nove Circulos." },
                { InstWelcomeIntro, "Este instalador ira:" },
                { InstWelcomeStep1, "- Pedir a pasta de destino" },
                { InstWelcomeStep2, "- Pedir a ISO original do jogo" },
                { InstWelcomeStep3, "- Extrair a ISO no destino" },
                { InstWelcomeStep4, "- Copiar os arquivos do port para PC" },
                { InstWelcomeStep5, "- Criar um atalho na area de trabalho" },
                { InstWelcomeLegal, "Voce deve possuir uma copia legal do disco ou ISO de Xbox 360." },
                { InstDestTitle, "Escolher Pasta de Instalacao" },
                { InstDestHint, "O jogo sera instalado nesta pasta." },
                { InstBrowse, "Procurar" },
                { InstIsoTitle, "Selecionar ISO do Jogo" },
                { InstIsoHint, "Selecione um arquivo ISO de Dante's Inferno para Xbox 360 (XISO)." },
                { InstProgressTitle, "Instalando..." },
                { InstFinishTitle, "Instalacao Concluida" },
                { InstCreateShortcut, "Criar atalho na area de trabalho" },
                { InstBack, "Voltar" },
                { InstNext, "Avancar" },
                { InstInstall, "Instalar" },
                { InstFinish, "Concluir" },
                { InstInvalidDestTitle, "Destino Invalido" },
                { InstInvalidDestMsg, "Escolha uma pasta de destino valida." },
                { InstInvalidIsoTitle, "ISO Invalida" },
                { InstInvalidIsoMsg, "Selecione um arquivo ISO valido." },
                { InstFolderDialog, "Selecione a pasta de instalacao" },
                { InstIsoDialog, "Selecione a ISO de Dante's Inferno" },
                { InstFailedTitle, "Erro de Instalacao" },
                { InstFailedMsg, "A instalacao falhou:\n{0}" },
                { InstShortcutErrorTitle, "Erro de Atalho" },
                { InstShortcutErrorMsg, "Nao foi possivel criar o atalho:\n{0}" },
                { InstFinishSummary, "Instalado em:\n{0}\n\nDados do jogo extraidos em:\n{1}\n\nClique em Concluir para fechar o instalador." },
                { InstPreparing, "Preparando destino..." },
                { InstRemovingOld, "Removendo dados antigos do jogo..." },
                { InstExtracting, "Extraindo a ISO para a pasta do jogo (pode demorar alguns minutos)..." },
                { InstSkipExtract, "Dados do jogo ja presentes, extracao ignorada." },
                { InstCopying, "Copiando arquivos do jogo..." },
                { InstCopied, "Copiado {0}" },
                { InstUpdatingConfig, "Atualizando configuracao..." },
                { InstCopyTu, "Copiando patch Title Update 2 (default.xexp)..." },
                { InstTuMissing, "AVISO: default.xexp nao encontrado no payload - TU2 nao sera aplicado." },
                { InstComplete, "Instalacao concluida." },
            };
            _translations["pt"] = pt;

            // French
            var fr = new Dictionary<string, string>
            {
                { TabPlay, "JOUER" },
                { TabDlc, "DLC" },
                { TabControls, "CONTROLES" },
                { TabSettings, "PARAMETRES" },
                { TabUpdates, "MAJ" },
                { PlaySubtitle, "Pret a entrer dans les Neuf Cercles." },
                { PlayStatusReady, "Fichiers du jeu trouves." },
                { PlayStatusMissing, "Fichiers du jeu manquants. Lancez l'installateur d'abord." },
                { TrialsServerTitle, "Trials of Saint Lucia - Serveur En Ligne" },
                { TrialsServerMessage, "Un serveur dedie pour le DLC Trials of Saint Lucia est actuellement en developpement et sera lance dans les prochains jours ou semaines. En raison des couts du serveur, l'acces sera limite aux membres Ko-Fi pour le moment. Surveillez notre Discord pour l'annonce du lancement." },
                { TrialsServerButton, "Soutenir sur Ko-Fi" },
                { PlayButton, "JOUER" },
                { ExitButton, "QUITTER" },
                { SupportDeveloper, "Soutenir le Developpeur" },
                { VersionLabel, "Version : {0}" },
                { DlcTitle, "Contenu Telechargeable" },
                { DlcDescription, "Pour installer le DLC, copiez vos fichiers de paquet STFS de DLC dans le dossier DLC, puis lancez le jeu. Le jeu les installera automatiquement au demarrage." },
                { OpenDlcFolder, "Ouvrir le Dossier DLC" },
                { OpenTuFolder, "Ouvrir le Dossier TU" },
                { DlcFolderEmpty, "Dossier DLC : vide" },
                { DlcFolderFound, "Dossier DLC : {0} fichier(s) trouve(s)" },
                { TuInstalled, "Mise a jour (default.xexp) : installee" },
                { TuNotFound, "Mise a jour (default.xexp) : introuvable" },
                { ControlsTitle, "Affectations Clavier" },
                { ControlsHint, "Cliquez sur un champ et appuyez sur une touche pour l'affecter. Utilisez des combinaisons comme Shift+Up pour le D-pad." },
                { GroupActions, "Actions" },
                { GroupShoulders, "Epaules / Gachettes" },
                { GroupLeftStick, "Stick Gauche (Deplacement)" },
                { GroupRightStick, "Stick Droit (Camera)" },
                { GroupDpad, "D-Pad" },
                { LabelA, "A (Interagir) :" },
                { LabelB, "B (Annuler) :" },
                { LabelX, "X (Attaquer) :" },
                { LabelY, "Y (Magie) :" },
                { LabelBack, "Retour :" },
                { LabelStart, "Start :" },
                { LabelLeftShoulder, "Epaule Gauche :" },
                { LabelRightShoulder, "Epaule Droite :" },
                { LabelLeftTrigger, "Gachette Gauche :" },
                { LabelRightTrigger, "Gachette Droite :" },
                { LabelUp, "Haut :" },
                { LabelDown, "Bas :" },
                { LabelLeft, "Gauche :" },
                { LabelRight, "Droite :" },
                { LabelPressSprint, "Appuyer (Sprint) :" },
                { LabelPress, "Appuyer :" },
                { BindingsAppliedNote, "Les affectations sont appliquees quand vous cliquez sur JOUER." },
                { ResetToDefault, "Restaurer par Defaut" },
                { SaveBindings, "Enregistrer les Affectations" },
                { GroupGraphics, "Qualite Graphique" },
                { LabelDisplay, "Affichage :" },
                { LabelResolution, "Resolution :" },
                { LabelRenderer, "Moteur de rendu :" },
                { LabelAntiAliasing, "Anti-Aliasing :" },
                { LabelTextureFiltering, "Filtrage des Textures :" },
                { LabelGameLanguage, "Langue du Jeu :" },
                { LabelLauncherLanguage, "Langue du Launcher :" },
                { CheckFullscreen, "Plein Ecran" },
                { GroupControls, "Controles" },
                { CheckControllerBackend, "Utiliser le backend de controleur SDL (Xbox / PlayStation)" },
                { LabelButtonGlyphs, "Glyphes de boutons :" },
                { ComingSoon, "Bientot disponible" },
                { CheckLogging, "Activer la journalisation (pour rapports de plantage)" },
                { SettingsAppliedNote, "Les parametres sont appliques quand vous cliquez sur JOUER." },
                { ResetToRecommended, "Restaurer les Parametres Recommandes" },
                { SaveSettings, "Enregistrer les Parametres" },
                { UpdatesTitle, "Verifier les Mises a Jour" },
                { InstalledVersion, "Version installee : {0}" },
                { CheckForUpdates, "Verifier les Mises a Jour" },
                { DownloadInstall, "Telecharger et Installer" },
                { ResolutionTooltip, "Resolution de rendu interne. 'Auto' correspond a la hauteur de votre ecran. Les autres valeurs sont des equivalents d'ecran; le jeu rend en 16:9 et est etire au format de votre moniteur." },
                { RendererTooltip, "ReXGlue = moteur de rendu D3D12 original. Native = moteur de rendu Vulkan Xenos in-process." },
                { LanguageGameTooltip, "Langue du jeu. Detectee depuis la region XEX du jeu. Anglais toujours disponible." },
                { LanguageLauncherTooltip, "Langue pour l'interface du launcher." },
                { TuFolderTooltip, "Ouvre le dossier du jeu ou default.xexp (Mise a Jour) doit etre place." },
                { ControllerTooltip, "Coche = SDL3 (toutes les familles de controleurs). Decoche = XInput (manettes Xbox uniquement)." },
                { GlyphTooltip, "Bientot disponible" },
                { InstTitle, "Dante's Inferno - Installateur" },
                { InstHeader, "DANTE'S INFERNO - INSTALLATEUR" },
                { InstWelcomeTitle, "Bienvenue dans les Neuf Cercles." },
                { InstWelcomeIntro, "Cet installateur va :" },
                { InstWelcomeStep1, "- Demander le dossier de destination" },
                { InstWelcomeStep2, "- Demander votre ISO originale du jeu" },
                { InstWelcomeStep3, "- Extraire l'ISO vers la destination" },
                { InstWelcomeStep4, "- Copier les fichiers du port PC" },
                { InstWelcomeStep5, "- Creer un raccourci bureau" },
                { InstWelcomeLegal, "Vous devez posseder une copie legale du disque ou de l'ISO Xbox 360." },
                { InstDestTitle, "Choisir le Dossier d'Installation" },
                { InstDestHint, "Le jeu sera installe dans ce dossier." },
                { InstBrowse, "Parcourir" },
                { InstIsoTitle, "Selectionner l'ISO du Jeu" },
                { InstIsoHint, "Selectionnez un fichier ISO Dante's Inferno Xbox 360 (XISO)." },
                { InstProgressTitle, "Installation..." },
                { InstFinishTitle, "Installation Terminee" },
                { InstCreateShortcut, "Creer un raccourci bureau" },
                { InstBack, "Retour" },
                { InstNext, "Suivant" },
                { InstInstall, "Installer" },
                { InstFinish, "Terminer" },
                { InstInvalidDestTitle, "Destination Invalide" },
                { InstInvalidDestMsg, "Veuillez choisir un dossier de destination valide." },
                { InstInvalidIsoTitle, "ISO Invalide" },
                { InstInvalidIsoMsg, "Veuillez selectionner un fichier ISO valide." },
                { InstFolderDialog, "Selectionnez le dossier d'installation" },
                { InstIsoDialog, "Selectionnez l'ISO de Dante's Inferno" },
                { InstFailedTitle, "Erreur d'Installation" },
                { InstFailedMsg, "L'installation a echoue :\n{0}" },
                { InstShortcutErrorTitle, "Erreur de Raccourci" },
                { InstShortcutErrorMsg, "Impossible de creer le raccourci bureau :\n{0}" },
                { InstFinishSummary, "Installe dans :\n{0}\n\nDonnees du jeu extraites dans :\n{1}\n\nCliquez sur Terminer pour fermer l'installateur." },
                { InstPreparing, "Preparation de la destination..." },
                { InstRemovingOld, "Suppression des anciennes donnees du jeu..." },
                { InstExtracting, "Extraction de l'ISO vers le dossier du jeu (cela peut prendre quelques minutes)..." },
                { InstSkipExtract, "Donnees du jeu deja presentes, extraction ignoree." },
                { InstCopying, "Copie des fichiers du jeu..." },
                { InstCopied, "Copie {0}" },
                { InstUpdatingConfig, "Mise a jour de la configuration..." },
                { InstCopyTu, "Copie du patch Title Update 2 (default.xexp)..." },
                { InstTuMissing, "AVERTISSEMENT : default.xexp introuvable dans le payload - TU2 ne sera pas applique." },
                { InstComplete, "Installation terminee." },
            };
            _translations["fr"] = fr;

            // Italian
            var it = new Dictionary<string, string>
            {
                { TabPlay, "GIOCA" },
                { TabDlc, "DLC" },
                { TabControls, "COMANDI" },
                { TabSettings, "IMPOSTAZIONI" },
                { TabUpdates, "AGGIORN." },
                { PlaySubtitle, "Pronto a entrare nei Nove Cerchi." },
                { PlayStatusReady, "File di gioco trovati." },
                { PlayStatusMissing, "File di gioco mancanti. Esegui prima l'installer." },
                { TrialsServerTitle, "Trials of Saint Lucia - Server Online" },
                { TrialsServerMessage, "Un server dedicato per il DLC Trials of Saint Lucia e attualmente in sviluppo e sara disponibile nei prossimi giorni o settimane. A causa dei costi del server, per ora l'accesso sara limitato ai membri Ko-Fi. Segui il nostro Discord per l'annuncio del lancio." },
                { TrialsServerButton, "Supporta su Ko-Fi" },
                { PlayButton, "GIOCA" },
                { ExitButton, "ESCI" },
                { SupportDeveloper, "Supporta lo Sviluppatore" },
                { VersionLabel, "Versione: {0}" },
                { DlcTitle, "Contenuti Scaricabili" },
                { DlcDescription, "Per installare i DLC, copia i file pacchetto STFS nella cartella DLC, poi avvia il gioco. Il gioco li installera automaticamente all'avvio." },
                { OpenDlcFolder, "Apri Cartella DLC" },
                { OpenTuFolder, "Apri Cartella TU" },
                { DlcFolderEmpty, "Cartella DLC: vuota" },
                { DlcFolderFound, "Cartella DLC: {0} file trovati" },
                { TuInstalled, "Title Update (default.xexp): installato" },
                { TuNotFound, "Title Update (default.xexp): non trovato" },
                { ControlsTitle, "Assegnazioni Tastiera" },
                { ControlsHint, "Clicca un campo e premi un tasto per assegnarlo. Usa combinazioni come Shift+Up per il D-pad." },
                { GroupActions, "Azioni" },
                { GroupShoulders, "Spalle / Trigger" },
                { GroupLeftStick, "Stick Sinistro (Movimento)" },
                { GroupRightStick, "Stick Destro (Camera)" },
                { GroupDpad, "D-Pad" },
                { LabelA, "A (Interagisci):" },
                { LabelB, "B (Annulla):" },
                { LabelX, "X (Attacco):" },
                { LabelY, "Y (Magia):" },
                { LabelBack, "Indietro:" },
                { LabelStart, "Start:" },
                { LabelLeftShoulder, "Spalla Sinistra:" },
                { LabelRightShoulder, "Spalla Destra:" },
                { LabelLeftTrigger, "Trigger Sinistro:" },
                { LabelRightTrigger, "Trigger Destro:" },
                { LabelUp, "Su:" },
                { LabelDown, "Giu:" },
                { LabelLeft, "Sinistra:" },
                { LabelRight, "Destra:" },
                { LabelPressSprint, "Premi (Scatto):" },
                { LabelPress, "Premi:" },
                { BindingsAppliedNote, "Le assegnazioni si applicano quando clicchi GIOCA." },
                { ResetToDefault, "Ripristina Predefinite" },
                { SaveBindings, "Salva Assegnazioni" },
                { GroupGraphics, "Qualita Grafica" },
                { LabelDisplay, "Schermo:" },
                { LabelResolution, "Risoluzione:" },
                { LabelRenderer, "Renderer:" },
                { LabelAntiAliasing, "Anti-Aliasing:" },
                { LabelTextureFiltering, "Filtro Texture:" },
                { LabelGameLanguage, "Lingua del Gioco:" },
                { LabelLauncherLanguage, "Lingua del Launcher:" },
                { CheckFullscreen, "Schermo Intero" },
                { GroupControls, "Controlli" },
                { CheckControllerBackend, "Usa backend controller SDL (Xbox / PlayStation)" },
                { LabelButtonGlyphs, "Glifi pulsanti:" },
                { ComingSoon, "Prossimamente" },
                { CheckLogging, "Abilita log (per report di crash)" },
                { SettingsAppliedNote, "Le impostazioni si applicano quando clicchi GIOCA." },
                { ResetToRecommended, "Ripristina Consigliate" },
                { SaveSettings, "Salva Impostazioni" },
                { UpdatesTitle, "Cerca Aggiornamenti" },
                { InstalledVersion, "Versione installata: {0}" },
                { CheckForUpdates, "Cerca Aggiornamenti" },
                { DownloadInstall, "Scarica e Installa" },
                { ResolutionTooltip, "Risoluzione di rendering interna. 'Auto' corrisponde all'altezza del monitor. Gli altri valori sono equivalenti display; il gioco renderizza in 16:9 e viene adattato al rapporto d'aspetto del monitor." },
                { RendererTooltip, "ReXGlue = renderer D3D12 originale. Native = renderer Vulkan Xenos in-process." },
                { LanguageGameTooltip, "Lingua del gioco. Solo le lingue presenti sul disco. L'inglese e disponibile se presente." },
                { LanguageLauncherTooltip, "Lingua dell'interfaccia del launcher." },
                { TuFolderTooltip, "Apre la cartella di gioco dove va collocato default.xexp (Title Update)." },
                { ControllerTooltip, "Selezionato = SDL3 (tutte le famiglie di controller). Deselezionato = XInput (solo pad Xbox)." },
                { GlyphTooltip, "Prossimamente" },
                { InstTitle, "Dante's Inferno - Installer" },
                { InstHeader, "DANTE'S INFERNO - INSTALLER" },
                { InstWelcomeTitle, "Benvenuto nei Nove Cerchi." },
                { InstWelcomeIntro, "Questo installer:" },
                { InstWelcomeStep1, "- Chiedera la cartella di destinazione" },
                { InstWelcomeStep2, "- Chiedera la ISO originale del gioco" },
                { InstWelcomeStep3, "- Estrarra la ISO nella destinazione" },
                { InstWelcomeStep4, "- Copiera i file del port PC" },
                { InstWelcomeStep5, "- Creera un collegamento sul desktop" },
                { InstWelcomeLegal, "Devi possedere una copia legale del disco o della ISO Xbox 360." },
                { InstDestTitle, "Scegli Cartella di Installazione" },
                { InstDestHint, "Il gioco verra installato in questa cartella." },
                { InstBrowse, "Sfoglia" },
                { InstIsoTitle, "Seleziona ISO del Gioco" },
                { InstIsoHint, "Seleziona un file ISO di Dante's Inferno per Xbox 360 (XISO)." },
                { InstProgressTitle, "Installazione in corso..." },
                { InstFinishTitle, "Installazione Completata" },
                { InstCreateShortcut, "Crea collegamento sul desktop" },
                { InstBack, "Indietro" },
                { InstNext, "Avanti" },
                { InstInstall, "Installa" },
                { InstFinish, "Fine" },
                { InstInvalidDestTitle, "Destinazione Non Valida" },
                { InstInvalidDestMsg, "Scegli una cartella di destinazione valida." },
                { InstInvalidIsoTitle, "ISO Non Valida" },
                { InstInvalidIsoMsg, "Seleziona un file ISO valido." },
                { InstFolderDialog, "Seleziona la cartella di installazione" },
                { InstIsoDialog, "Seleziona la ISO di Dante's Inferno" },
                { InstFailedTitle, "Errore di Installazione" },
                { InstFailedMsg, "Installazione non riuscita:\n{0}" },
                { InstShortcutErrorTitle, "Errore Collegamento" },
                { InstShortcutErrorMsg, "Impossibile creare il collegamento sul desktop:\n{0}" },
                { InstFinishSummary, "Installato in:\n{0}\n\nDati di gioco estratti in:\n{1}\n\nClicca Fine per chiudere l'installer." },
                { InstPreparing, "Preparazione destinazione..." },
                { InstRemovingOld, "Rimozione dati di gioco precedenti..." },
                { InstExtracting, "Estrazione ISO nella cartella di gioco (puo richiedere alcuni minuti)..." },
                { InstSkipExtract, "Dati di gioco gia presenti, estrazione saltata." },
                { InstCopying, "Copia file di gioco..." },
                { InstCopied, "Copiato {0}" },
                { InstUpdatingConfig, "Aggiornamento configurazione..." },
                { InstCopyTu, "Copia patch Title Update 2 (default.xexp)..." },
                { InstTuMissing, "AVVISO: default.xexp non trovato nel payload - TU2 non verra applicato." },
                { InstComplete, "Installazione completata." },
            };
            _translations["it"] = it;
        }

        /// <summary>
        /// Returns the localized string for the given key, or the key itself if not found.
        /// </summary>
        public static string Get(string language, string key)
        {
            if (_translations.TryGetValue(language, out var lang) &&
                lang.TryGetValue(key, out var value) && !string.IsNullOrEmpty(value))
                return value;
            // Fallback to English
            if (_translations.TryGetValue(DefaultLanguage, out var en) &&
                en.TryGetValue(key, out var enValue))
                return enValue;
            return key;
        }

        /// <summary>
        /// Returns the localized string formatted with the given args.
        /// </summary>
        public static string Get(string language, string key, params object[] args)
        {
            string template = Get(language, key);
            try { return string.Format(template, args); }
            catch { return template; }
        }

        /// <summary>
        /// Normalizes a language code to one of the supported languages.
        /// </summary>
        public static string NormalizeLanguage(string language)
        {
            if (string.IsNullOrEmpty(language))
                return DefaultLanguage;
            string lang = language.ToLowerInvariant();
            if (SupportedLanguages.Contains(lang))
                return lang;
            // Handle full names / aliases
            if (lang == "italian" || lang == "italiano")
                return "it";
            foreach (var kvp in LanguageDisplayNames)
            {
                if (kvp.Value.Equals(language, StringComparison.OrdinalIgnoreCase))
                    return kvp.Key;
            }
            return DefaultLanguage;
        }
    }
}
